import torch

BATCH_SIZE = 16
NUM_EPOCH = 30
ENCODER_LEARNING_RATE = 1e-4
DECODER_LEARNING_RATE = 1e-4
TEACHER_FORCE_RATIO = 0.5

TRANSFORMER_BATCH_SIZE=1
TRANSFORMER_LEARNING_RATE = 5e-4
NUM_HEADS=2

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'